export { default as blue } from './blue'
export { default as blueGrey } from './blueGrey'
export { default as common } from './common'
export { default as grey } from './grey'
export { default as red } from './red'
