import cartSelection from './cartSelection'

export default Array.from(new Array(3), () => ({
  order: '38463',
  status: 'untouched',
  statusDescription: 'Pending',
  date: '2021-06-08 15:31:49',
  language: 'sv',
  currency: 'SEK',
  paymentMethod: 'kco',
  paymentMethodName: 'Klarna',
  shippingMethod: 'dhl',
  shippingMethodName: 'DHL',
  items: cartSelection.items,
  discounts: cartSelection.discounts,
  totals: cartSelection.totals,
  vatExempt: false,
  address: {
    email: 'joe@doe.com',
    firstName: 'Jon',
    lastName: 'Doe',
    company: '',
    address1: 'My address 32',
    address2: '',
    zipCode: '13123',
    city: 'Stockholm',
    state: '',
    country: 'SE',
    countryName: 'Sweden',
    phoneNumber: '+46731234567',
    vatNumber: '',
  },
  shippingAddress: {
    email: 'joe@doe.com',
    firstName: 'Jon',
    lastName: 'Doe',
    company: '',
    address1: 'My address 32',
    address2: '',
    zipCode: '13123',
    city: 'Stockholm',
    state: '',
    country: 'SE',
    countryName: 'Sweden',
    phoneNumber: '+46731234567',
  },
  giftMessage: '',
  additionalNotes: '',
  currencyFormat: cartSelection.currencyFormat,
}))
